### ISSUE TITLE
The docs target should not be generated if Doxygen is not available

### ISSUE THREAD

**Issue by alexrj** [italia/cie-nis-cpp-sdk#41] opened 2018-04-14 15:11 UTC
`./configure` detects lack of Doxygen correctly, but `make` still tries to do the _docs_ target but fails. It should not attempt to build _docs_ if Doxygen is not installed. See the full output below.

```
staff@spring2:~/cie-nis-cpp-sdk$ ./configure
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... no
checking for mawk... mawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking for style of include used by make... GNU
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking dependency style of gcc... gcc3
checking for ar... ar
checking the archiver (ar) interface... ar
checking for gcc... (cached) gcc
checking whether we are using the GNU C compiler... (cached) yes
checking whether gcc accepts -g... (cached) yes
checking for gcc option to accept ISO C89... (cached) none needed
checking whether gcc understands -c and -o together... (cached) yes
checking dependency style of gcc... (cached) gcc3
checking for g++... g++
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking dependency style of g++... gcc3
checking for SCardConnect in -lpcsclite... yes
checking for library containing SCardConnect... none required
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for PCSC... yes
checking for doxygen... no
configure: WARNING: Doxygen not found - continuing without Doxygen support
checking for atexit... yes
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking stddef.h usability... yes
checking stddef.h presence... yes
checking for stddef.h... yes
checking for stdbool.h that conforms to C99... yes
checking for _Bool... yes
checking for size_t... yes
checking for uint32_t... yes
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking how to print strings... printf
checking for a sed that does not truncate output... /bin/sed
checking for fgrep... /bin/grep -F
checking for ld used by gcc... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
checking the name lister (/usr/bin/nm -B) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 1572864
checking whether the shell understands some XSI constructs... yes
checking whether the shell understands "+="... yes
checking how to convert x86_64-unknown-linux-gnu file names to x86_64-unknown-linux-gnu format... func_convert_file_noop
checking how to convert x86_64-unknown-linux-gnu file names to toolchain format... func_convert_file_noop
checking for /usr/bin/ld option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for archiver @FILE support... @
checking for strip... strip
checking for ranlib... ranlib
checking command to parse /usr/bin/nm -B output from gcc object... ok
checking for sysroot... no
checking for mt... mt
checking if mt is a manifest tool... no
checking for dlfcn.h... yes
checking for objdir... .libs
checking if gcc supports -fno-rtti -fno-exceptions... no
checking for gcc option to produce PIC... -fPIC -DPIC
checking if gcc PIC flag -fPIC -DPIC works... yes
checking if gcc static flag -static works... no
checking if gcc supports -c -o file.o... yes
checking if gcc supports -c -o file.o... (cached) yes
checking whether the gcc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... yes
checking how to run the C++ preprocessor... g++ -E
checking for ld used by g++... /usr/bin/ld -m elf_x86_64
checking if the linker (/usr/bin/ld -m elf_x86_64) is GNU ld... yes
checking whether the g++ linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking for g++ option to produce PIC... -fPIC -DPIC
checking if g++ PIC flag -fPIC -DPIC works... yes
checking if g++ static flag -static works... no
checking if g++ supports -c -o file.o... yes
checking if g++ supports -c -o file.o... (cached) yes
checking whether the g++ linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking dynamic linker characteristics... (cached) GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating src/Makefile
config.status: creating config.h
config.status: config.h is unchanged
config.status: executing depfiles commands
config.status: executing libtool commands
staff@spring2:~/cie-nis-cpp-sdk$ make
make  all-recursive
make[1]: Entering directory `/home/staff/cie-nis-cpp-sdk'
Making all in src
make[2]: Entering directory `/home/staff/cie-nis-cpp-sdk/src'
/bin/bash ../libtool  --tag=CXX   --mode=compile g++ -DHAVE_CONFIG_H -I. -I..  -pthread -I/usr/include/PCSC    -g -O2 -std=c++11 -g -O2 -MT libcienis_la-nis.lo -MD -MP -MF .deps/libcienis_la-nis.Tpo -c -o libcienis_la-nis.lo `test -f 'nis.cpp' || echo './'`nis.cpp
libtool: compile:  g++ -DHAVE_CONFIG_H -I. -I.. -pthread -I/usr/include/PCSC -g -O2 -std=c++11 -g -O2 -MT libcienis_la-nis.lo -MD -MP -MF .deps/libcienis_la-nis.Tpo -c nis.cpp  -fPIC -DPIC -o .libs/libcienis_la-nis.o
libtool: compile:  g++ -DHAVE_CONFIG_H -I. -I.. -pthread -I/usr/include/PCSC -g -O2 -std=c++11 -g -O2 -MT libcienis_la-nis.lo -MD -MP -MF .deps/libcienis_la-nis.Tpo -c nis.cpp -o libcienis_la-nis.o >/dev/null 2>&1
mv -f .deps/libcienis_la-nis.Tpo .deps/libcienis_la-nis.Plo
/bin/bash ../libtool  --tag=CXX   --mode=compile g++ -DHAVE_CONFIG_H -I. -I..  -pthread -I/usr/include/PCSC    -g -O2 -std=c++11 -g -O2 -MT libcienis_la-nis_manager.lo -MD -MP -MF .deps/libcienis_la-nis_manager.Tpo -c -o libcienis_la-nis_manager.lo `test -f 'nis_manager.cpp' || echo './'`nis_manager.cpp
libtool: compile:  g++ -DHAVE_CONFIG_H -I. -I.. -pthread -I/usr/include/PCSC -g -O2 -std=c++11 -g -O2 -MT libcienis_la-nis_manager.lo -MD -MP -MF .deps/libcienis_la-nis_manager.Tpo -c nis_manager.cpp  -fPIC -DPIC -o .libs/libcienis_la-nis_manager.o
libtool: compile:  g++ -DHAVE_CONFIG_H -I. -I.. -pthread -I/usr/include/PCSC -g -O2 -std=c++11 -g -O2 -MT libcienis_la-nis_manager.lo -MD -MP -MF .deps/libcienis_la-nis_manager.Tpo -c nis_manager.cpp -o libcienis_la-nis_manager.o >/dev/null 2>&1
mv -f .deps/libcienis_la-nis_manager.Tpo .deps/libcienis_la-nis_manager.Plo
/bin/bash ../libtool  --tag=CXX   --mode=compile g++ -DHAVE_CONFIG_H -I. -I..  -pthread -I/usr/include/PCSC    -g -O2 -std=c++11 -g -O2 -MT libcienis_la-reader.lo -MD -MP -MF .deps/libcienis_la-reader.Tpo -c -o libcienis_la-reader.lo `test -f 'reader.cpp' || echo './'`reader.cpp
libtool: compile:  g++ -DHAVE_CONFIG_H -I. -I.. -pthread -I/usr/include/PCSC -g -O2 -std=c++11 -g -O2 -MT libcienis_la-reader.lo -MD -MP -MF .deps/libcienis_la-reader.Tpo -c reader.cpp  -fPIC -DPIC -o .libs/libcienis_la-reader.o
libtool: compile:  g++ -DHAVE_CONFIG_H -I. -I.. -pthread -I/usr/include/PCSC -g -O2 -std=c++11 -g -O2 -MT libcienis_la-reader.lo -MD -MP -MF .deps/libcienis_la-reader.Tpo -c reader.cpp -o libcienis_la-reader.o >/dev/null 2>&1
mv -f .deps/libcienis_la-reader.Tpo .deps/libcienis_la-reader.Plo
/bin/bash ../libtool  --tag=CXX   --mode=compile g++ -DHAVE_CONFIG_H -I. -I..  -pthread -I/usr/include/PCSC    -g -O2 -std=c++11 -g -O2 -MT libcienis_la-reader_pcsc.lo -MD -MP -MF .deps/libcienis_la-reader_pcsc.Tpo -c -o libcienis_la-reader_pcsc.lo `test -f 'reader_pcsc.cpp' || echo './'`reader_pcsc.cpp
libtool: compile:  g++ -DHAVE_CONFIG_H -I. -I.. -pthread -I/usr/include/PCSC -g -O2 -std=c++11 -g -O2 -MT libcienis_la-reader_pcsc.lo -MD -MP -MF .deps/libcienis_la-reader_pcsc.Tpo -c reader_pcsc.cpp  -fPIC -DPIC -o .libs/libcienis_la-reader_pcsc.o
libtool: compile:  g++ -DHAVE_CONFIG_H -I. -I.. -pthread -I/usr/include/PCSC -g -O2 -std=c++11 -g -O2 -MT libcienis_la-reader_pcsc.lo -MD -MP -MF .deps/libcienis_la-reader_pcsc.Tpo -c reader_pcsc.cpp -o libcienis_la-reader_pcsc.o >/dev/null 2>&1
mv -f .deps/libcienis_la-reader_pcsc.Tpo .deps/libcienis_la-reader_pcsc.Plo
/bin/bash ../libtool  --tag=CXX   --mode=compile g++ -DHAVE_CONFIG_H -I. -I..  -pthread -I/usr/include/PCSC    -g -O2 -std=c++11 -g -O2 -MT libcienis_la-requests.lo -MD -MP -MF .deps/libcienis_la-requests.Tpo -c -o libcienis_la-requests.lo `test -f 'requests.cpp' || echo './'`requests.cpp
libtool: compile:  g++ -DHAVE_CONFIG_H -I. -I.. -pthread -I/usr/include/PCSC -g -O2 -std=c++11 -g -O2 -MT libcienis_la-requests.lo -MD -MP -MF .deps/libcienis_la-requests.Tpo -c requests.cpp  -fPIC -DPIC -o .libs/libcienis_la-requests.o
libtool: compile:  g++ -DHAVE_CONFIG_H -I. -I.. -pthread -I/usr/include/PCSC -g -O2 -std=c++11 -g -O2 -MT libcienis_la-requests.lo -MD -MP -MF .deps/libcienis_la-requests.Tpo -c requests.cpp -o libcienis_la-requests.o >/dev/null 2>&1
mv -f .deps/libcienis_la-requests.Tpo .deps/libcienis_la-requests.Plo
/bin/bash ../libtool  --tag=CXX   --mode=compile g++ -DHAVE_CONFIG_H -I. -I..  -pthread -I/usr/include/PCSC    -g -O2 -std=c++11 -g -O2 -MT libcienis_la-token.lo -MD -MP -MF .deps/libcienis_la-token.Tpo -c -o libcienis_la-token.lo `test -f 'token.cpp' || echo './'`token.cpp
libtool: compile:  g++ -DHAVE_CONFIG_H -I. -I.. -pthread -I/usr/include/PCSC -g -O2 -std=c++11 -g -O2 -MT libcienis_la-token.lo -MD -MP -MF .deps/libcienis_la-token.Tpo -c token.cpp  -fPIC -DPIC -o .libs/libcienis_la-token.o
libtool: compile:  g++ -DHAVE_CONFIG_H -I. -I.. -pthread -I/usr/include/PCSC -g -O2 -std=c++11 -g -O2 -MT libcienis_la-token.lo -MD -MP -MF .deps/libcienis_la-token.Tpo -c token.cpp -o libcienis_la-token.o >/dev/null 2>&1
mv -f .deps/libcienis_la-token.Tpo .deps/libcienis_la-token.Plo
/bin/bash ../libtool  --tag=CXX   --mode=compile g++ -DHAVE_CONFIG_H -I. -I..  -pthread -I/usr/include/PCSC    -g -O2 -std=c++11 -g -O2 -MT libcienis_la-token_pcsc.lo -MD -MP -MF .deps/libcienis_la-token_pcsc.Tpo -c -o libcienis_la-token_pcsc.lo `test -f 'token_pcsc.cpp' || echo './'`token_pcsc.cpp
libtool: compile:  g++ -DHAVE_CONFIG_H -I. -I.. -pthread -I/usr/include/PCSC -g -O2 -std=c++11 -g -O2 -MT libcienis_la-token_pcsc.lo -MD -MP -MF .deps/libcienis_la-token_pcsc.Tpo -c token_pcsc.cpp  -fPIC -DPIC -o .libs/libcienis_la-token_pcsc.o
libtool: compile:  g++ -DHAVE_CONFIG_H -I. -I.. -pthread -I/usr/include/PCSC -g -O2 -std=c++11 -g -O2 -MT libcienis_la-token_pcsc.lo -MD -MP -MF .deps/libcienis_la-token_pcsc.Tpo -c token_pcsc.cpp -o libcienis_la-token_pcsc.o >/dev/null 2>&1
mv -f .deps/libcienis_la-token_pcsc.Tpo .deps/libcienis_la-token_pcsc.Plo
/bin/bash ../libtool  --tag=CXX   --mode=link g++ -g -O2 -std=c++11 -g -O2 -version.info 1:0:0 -lpcsclite    -o libcienis.la -rpath /usr/local/lib libcienis_la-nis.lo libcienis_la-nis_manager.lo libcienis_la-reader.lo libcienis_la-reader_pcsc.lo libcienis_la-requests.lo libcienis_la-token.lo libcienis_la-token_pcsc.lo  -lpcsclite
libtool: link: g++  -fPIC -DPIC -shared -nostdlib /usr/lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu/crti.o /usr/lib/gcc/x86_64-linux-gnu/4.8/crtbeginS.o  .libs/libcienis_la-nis.o .libs/libcienis_la-nis_manager.o .libs/libcienis_la-reader.o .libs/libcienis_la-reader_pcsc.o .libs/libcienis_la-requests.o .libs/libcienis_la-token.o .libs/libcienis_la-token_pcsc.o   -lpcsclite -L/usr/lib/gcc/x86_64-linux-gnu/4.8 -L/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu -L/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../../lib -L/lib/x86_64-linux-gnu -L/lib/../lib -L/usr/lib/x86_64-linux-gnu -L/usr/lib/../lib -L/usr/lib/gcc/x86_64-linux-gnu/4.8/../../.. -lstdc++ -lm -lc -lgcc_s /usr/lib/gcc/x86_64-linux-gnu/4.8/crtendS.o /usr/lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu/crtn.o  -O2 -O2   -Wl,-soname -Wl,libcienis.so.0 -o .libs/libcienis.so.0.0.0
libtool: link: (cd ".libs" && rm -f "libcienis.so.0" && ln -s "libcienis.so.0.0.0" "libcienis.so.0")
libtool: link: (cd ".libs" && rm -f "libcienis.so" && ln -s "libcienis.so.0.0.0" "libcienis.so")
libtool: link: ar cru .libs/libcienis.a  libcienis_la-nis.o libcienis_la-nis_manager.o libcienis_la-reader.o libcienis_la-reader_pcsc.o libcienis_la-requests.o libcienis_la-token.o libcienis_la-token_pcsc.o
libtool: link: ranlib .libs/libcienis.a
libtool: link: ( cd ".libs" && rm -f "libcienis.la" && ln -s "../libcienis.la" "libcienis.la" )
gcc -DHAVE_CONFIG_H -I. -I..  -pthread -I/usr/include/PCSC     -g -O2 -MT test/testnisc-example-nis-c.o -MD -MP -MF test/.deps/testnisc-example-nis-c.Tpo -c -o test/testnisc-example-nis-c.o `test -f 'test/example-nis-c.c' || echo './'`test/example-nis-c.c
mv -f test/.deps/testnisc-example-nis-c.Tpo test/.deps/testnisc-example-nis-c.Po
/bin/bash ../libtool  --tag=CC   --mode=link gcc  -g -O2   -o testnisc test/testnisc-example-nis-c.o libcienis.la -lpcsclite
libtool: link: gcc -g -O2 -o .libs/testnisc test/testnisc-example-nis-c.o  ./.libs/libcienis.so -lpcsclite
g++ -DHAVE_CONFIG_H -I. -I..  -pthread -I/usr/include/PCSC    -g -O2 -std=c++11 -g -O2 -MT test/testniscpp-example-nis-cpp.o -MD -MP -MF test/.deps/testniscpp-example-nis-cpp.Tpo -c -o test/testniscpp-example-nis-cpp.o `test -f 'test/example-nis-cpp.cpp' || echo './'`test/example-nis-cpp.cpp
mv -f test/.deps/testniscpp-example-nis-cpp.Tpo test/.deps/testniscpp-example-nis-cpp.Po
/bin/bash ../libtool  --tag=CXX   --mode=link g++ -g -O2 -std=c++11 -g -O2   -o testniscpp test/testniscpp-example-nis-cpp.o libcienis.la -lpcsclite
libtool: link: g++ -g -O2 -std=c++11 -g -O2 -o .libs/testniscpp test/testniscpp-example-nis-cpp.o  ./.libs/libcienis.so -lpcsclite
make[2]: Leaving directory `/home/staff/cie-nis-cpp-sdk/src'
Making all in docs
make[2]: Entering directory `/home/staff/cie-nis-cpp-sdk/docs'
make[2]: *** No rule to make target `all'.  Stop.
make[2]: Leaving directory `/home/staff/cie-nis-cpp-sdk/docs'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/home/staff/cie-nis-cpp-sdk'
make: *** [all] Error 2
```

**Comment by jmc-88** [comment] 2018-06-30 12:06
I believe this is now taken care of as part of the move to CMake:

- The [`BUILD_DOCUMENTATION`](https://github.com/italia/cie-nis-cpp-sdk/blob/08121f84152a2cfec06af3e5a395672cbb7f9899/CMakeLists.txt#L25) option is enabled by default only if Doxygen is found
- If that option is false, [documentation is not built](https://github.com/italia/cie-nis-cpp-sdk/blob/08121f84152a2cfec06af3e5a395672cbb7f9899/docs/CMakeLists.txt#L1)

**Comment by sfaragnaus** [comment] 2018-06-30 16:32
It seems that the culprit is find_package(Doxygen) in the root CMakeFile. Set DOXYGEN_FOUND even if the executable is not there. I'm investigating further.

**Comment by jmc-88** [comment] 2018-07-01 13:40
@sfaragnaus: are you sure about that? I can't reproduce the issue you mentioned. I've done the following:
-  uninstalled `doxygen`
-  recreated the build directory
-  built the project

The documentation was correctly skipped in that case.

I think what you mentioned could occur in the case where the user has created and initialized a build directory with `doxygen` installed, then subsequently uninstalled `doxygen` and tried to build again: in that case the CMake cache still has the `BUILD_DOCUMENTATION` option enabled even if `doxygen` has disappeared. Doesn't sound like a big issue to me (the user can change the cache with `ccmake` afterwards if they don't want to recreate the build directory).

**Comment by sfaragnaus** [comment] 2018-07-01 19:06
Checked with and without doxygen, starting from a fresh build directory. You are right, indeed. Closing since the bug does not subsist.

**Closed by sfaragnaus** 2018-07-01 19:06 UTC
Labels: bug
